# Generated by Django 4.2.4 on 2023-09-09 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_post_likes_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
